# Generated by Django 4.2.11 on 2024-05-21 19:24

from django.db import migrations, models
import website.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketingFormView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(help_text='نام', max_length=255)),
                ('last_name', models.CharField(help_text='نام خانوادگی', max_length=255)),
                ('email_address', models.EmailField(help_text='ادرس ایمیل', max_length=254)),
                ('mobile_number', models.IntegerField(help_text='شماره موبایل', max_length=11, validators=[website.validators.validate_iranian_cellphone_number])),
                ('subject', models.CharField(help_text='موضوع', max_length=255)),
                ('message', models.TextField(help_text='پیغام')),
                ('created_at', models.DateTimeField(auto_now=True, help_text='تاریخ تولید پیغام')),
            ],
        ),
    ]
