# Generated by Django 4.2.11 on 2024-05-21 19:24

from django.db import migrations, models
import website.validators


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketingformview',
            name='mobile_number',
            field=models.CharField(help_text='شماره موبایل', max_length=11, validators=[website.validators.validate_iranian_cellphone_number]),
        ),
    ]
