# Generated by Django 4.2.11 on 2024-05-21 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_ticketingformview_mobile_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TicketingFormView',
            new_name='TicketingFormModel',
        ),
    ]
