# Generated by Django 4.2.11 on 2024-05-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_ticketingformview_ticketingformmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketingformmodel',
            name='ticket_id',
        ),
    ]
