# Generated by Django 4.2.11 on 2024-05-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_ticketingformmodel_ticket_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='ایمیل عضویت در خبر نامه', max_length=254)),
                ('created_at', models.DateTimeField(auto_now=True, help_text='تاریخ  عضویت')),
            ],
        ),
    ]
