# Generated by Django 4.2.11 on 2024-06-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentmodel_payment_gateway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='recipt_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
